/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIDemo_JNIDemo */

#ifndef _Included_JNIDemo_JNIDemo
#define _Included_JNIDemo_JNIDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIDemo_JNIDemo
 * Method:    nativePrint
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNIDemo_JNIDemo_nativePrint
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
